mod-2-code-alongs/routes-playground/config/routes.rb
Rails.application.routes.draw do
  # scope '/admin', module: "admin" do
  #   resources :instruments, param: :name
  # end

  # scope module: "admin" do
  #   resources :instruments, param: :name
  # end

  # namespace "admin" do
  #   resources :instruments
    #This does url, path helper, and controller inheritance
  # end

  resources :instruments do
    resources :books
  end

end

mod-2-code-alongs/routes-playground/app/models/book.rb
class Book < ActiveRecord::Base
  belongs_to :instrument
end

mod-2-code-alongs/routes-playground/app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :books
end

mod-2-code-alongs/routes-playground/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

mod-2-code-alongs/routes-playground/app/controllers/instruments_controller.rb
class InstrumentController < ApplicationController

  def show
    @instrument = Instrument.find_by(name: params[:name])
  end
end

mod-2-code-alongs/routes-playground/app/helpers/instrument_helper.rb
module InstrumentHelper
end

mod-2-code-alongs/routes-playground/app/views/instruments/index.html.erb
<% instruments.each do |instrument| %>
  <%= link_to "Show this instrument", instrument_path(instrument) %>
<% end %>

mod-2-code-alongs/routes-playground/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RoutesPlayground</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>